<?php

if (!function_exists('GetDefaultFromFile')) {
    function GetDefaultFromFile(string $path): string
    {
        return '<pre style="max-width:1000px;white-space:pre-wrap">'
            . htmlspecialchars(file_get_contents(__DIR__ . '/area_default/' . $path))
            . '</pre>';
    }
}

return [
    'directory' => 'include_area',
    'groups' => [
        'template_ru' => [
            'name' => 'Шаблон сайта (RU)',
            'sort' => 100,
        ],
        'home_ru' => [
            'name' => 'Главная (RU)',
            'sort' => 200,
        ],
        'product_ru' => [
            'name' => 'Продукт (RU)',
            'sort' => 300,
        ],
        'about_ru' => [
            'name' => 'О бренде (RU)',
            'sort' => 400,
        ],
        'contacts_ru' => [
            'name' => 'Контакты (RU)',
            'sort' => 500,
        ],
        'shops_ru' => [
            'name' => 'Магазины (RU)',
            'sort' => 600,
        ],
        'template_en' => [
            'name' => 'Шаблон сайта (EN)',
            'sort' => 101,
        ],
        'home_en' => [
            'name' => 'Главная (EN)',
            'sort' => 201,
        ],
        'product_en' => [
            'name' => 'Продукт (EN)',
            'sort' => 301,
        ],
        'about_en' => [
            'name' => 'О бренде (EN)',
            'sort' => 401,
        ],
        'contacts_en' => [
            'name' => 'Контакты (EN)',
            'sort' => 501,
        ],
        'shops_en' => [
            'name' => 'Магазины (EN)',
            'sort' => 601,
        ],
    ],
    'files' => [
        [
            'name' => 'Телефон',
            'sort' => 1000,
            'group' => 'template_ru',
            'path' => 'ru/template_phone.php',
            'type' => 'string',
            'default' => '8 800 600 32 69',
        ],
        [
            'name' => 'Email',
            'sort' => 1050,
            'group' => 'template_ru',
            'path' => 'ru/template_email.php',
            'type' => 'string',
            'default' => 'info@lejournalintime.com',
        ],
        [
            'name' => 'Telegram',
            'sort' => 1100,
            'group' => 'template_ru',
            'path' => 'ru/template_telegram.php',
            'type' => 'string',
            'default' => 'https://t.me/le_journal_intime',
        ],
        [
            'name' => 'Вконтакте',
            'sort' => 1200,
            'group' => 'template_ru',
            'path' => 'ru/template_vk.php',
            'type' => 'string',
            'default' => 'https://vk.com/le_journal_intime',
        ],
        [
            'name' => 'Whatsapp',
            'sort' => 1300,
            'group' => 'template_ru',
            'path' => 'ru/template_whatsapp.php',
            'type' => 'string',
            'default' => 'https://wa.me/88006003269',
        ],
        [
            'name' => 'YouTube',
            'sort' => 1400,
            'group' => 'template_ru',
            'path' => 'ru/template_youtube.php',
            'type' => 'string',
            'default' => '',
        ],
        [
            'name' => 'Микроразметка',
            'sort' => 1500,
            'group' => 'template_ru',
            'path' => 'ru/template_schema.php',
            'lines' => [
                'Организация: название',
                'Организация: описание',
                'Организация: url',
                'Организация: телефон',
                'Организация: email',
                'Адрес: индекс',
                'Адрес: страна',
                'Адрес: регион',
                'Адрес: город\село',
                'Адрес: адрес',
            ],
            'default' => 'Lejournal intime \ https://lejournalintime.com \ +78006003269 \ shop@lejournalintime.com \ 125493 Россия Москва ул.Авангардная д3 офис 1107',
        ],
        [
            'name' => 'Микроразметка (изображение)',
            'sort' => 1600,
            'group' => 'template_ru',
            'path' => 'ru/template_schema_image.php',
            'type' => 'image',
            'default' => '',
        ],
        [
            'name' => 'Заголовок H1',
            'sort' => 2000,
            'group' => 'home_ru',
            'path' => 'ru/main_h1.php',
            'type' => 'string',
            'default' => 'Winter Refresh: The Essential Sophia Lingerie',
        ],
        [
            'name' => 'Адрес флагманского магазина',
            'sort' => 2100,
            'group' => 'home_ru',
            'path' => 'ru/main_head_shop_address.php',
            'type' => 'string',
            'default' => 'Большая Никитская, 14',
        ],
        [
            'name' => 'Изображение флагманского магазина',
            'sort' => 2110,
            'group' => 'home_ru',
            'path' => 'ru/main_head_shop_image.php',
            'type' => 'image',
            'default' => '<img src="/assets/img/showroom-section/background-1.jpg" alt="" width="500">',
        ],
        [
            'name' => 'Доставка (модальное окно)',
            'sort' => 3000,
            'group' => 'product_ru',
            'path' => 'ru/product_modal_delivery.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/product_modal_delivery.php'),
        ],
        [
            'name' => 'Доставка: ссылка на условия возврата (модальное окно)',
            'sort' => 3100,
            'group' => 'product_ru',
            'path' => 'ru/product_modal_delivery_return_link.php',
            'type' => 'string',
            'default' => '',
        ],
        [
            'name' => 'Оплата (модальное окно)',
            'sort' => 3200,
            'group' => 'product_ru',
            'path' => 'ru/product_modal_payment.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/product_modal_payment.php'),
        ],
        [
            'name' => 'О нас',
            'sort' => 4000,
            'group' => 'about_ru',
            'path' => 'ru/about_intro.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/about_intro.php'),
        ],
        [
            'name' => 'Создатели',
            'sort' => 4100,
            'group' => 'about_ru',
            'path' => 'ru/about_vendor.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/about_vendor.php'),
        ],
        [
            'name' => 'Создатели (справа)',
            'sort' => 4101,
            'group' => 'about_ru',
            'path' => 'ru/about_vendor_2.php',
            'type' => 'html',
            'default' => '',
        ],
        [
            'name' => 'Признание в обществе',
            'sort' => 4200,
            'group' => 'about_ru',
            'path' => 'ru/about_media.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/about_media.php'),
        ],
        [
            'name' => 'Наши друзья',
            'sort' => 4400,
            'group' => 'about_ru',
            'path' => 'ru/about_friends.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/about_friends.php'),
        ],
        [
            'name' => 'Наименование компании',
            'sort' => 5000,
            'group' => 'contacts_ru',
            'path' => 'ru/contacts_company.php',
            'type' => 'string',
            'default' => 'ООО «Нэйтив»',
        ],
        [
            'name' => 'Реквизиты',
            'sort' => 5100,
            'group' => 'contacts_ru',
            'path' => 'ru/contacts_requisites.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('ru/contacts_requisites.php'),
        ],
        [
            'name' => 'Магазины партнеров (изображение)',
            'sort' => 6000,
            'group' => 'shops_ru',
            'path' => 'ru/shops_sales_locations.php',
            'type' => 'image',
            'default' => '<img src="/assets/img/showrooms/showroom-2.jpg" alt="" width="500">',
        ],
        [
            'name' => 'Телефон',
            'sort' => 1001,
            'group' => 'template_en',
            'path' => 'en/template_phone.php',
            'type' => 'string',
            'default' => '8 800 600 32 69',
        ],
        [
            'name' => 'Email',
            'sort' => 1051,
            'group' => 'template_en',
            'path' => 'en/template_email.php',
            'type' => 'string',
            'default' => 'info@lejournalintime.com',
        ],
        [
            'name' => 'Telegram',
            'sort' => 1101,
            'group' => 'template_en',
            'path' => 'en/template_telegram.php',
            'type' => 'string',
            'default' => 'https://t.me/le_journal_intime',
        ],
        [
            'name' => 'Вконтакте',
            'sort' => 1201,
            'group' => 'template_en',
            'path' => 'en/template_vk.php',
            'type' => 'string',
            'default' => 'https://vk.com/le_journal_intime',
        ],
        [
            'name' => 'Whatsapp',
            'sort' => 1301,
            'group' => 'template_en',
            'path' => 'en/template_whatsapp.php',
            'type' => 'string',
            'default' => 'https://wa.me/88006003269',
        ],
        [
            'name' => 'YouTube',
            'sort' => 1401,
            'group' => 'template_en',
            'path' => 'en/template_youtube.php',
            'type' => 'string',
            'default' => '',
        ],
        [
            'name' => 'Микроразметка',
            'sort' => 1501,
            'group' => 'template_en',
            'path' => 'en/template_schema.php',
            'lines' => [
                'Организация: название',
                'Организация: описание',
                'Организация: url',
                'Организация: телефон',
                'Организация: email',
                'Адрес: индекс',
                'Адрес: страна',
                'Адрес: регион',
                'Адрес: город\село',
                'Адрес: адрес',
            ],
            'default' => 'Lejournal intime \ https://lejournalintime.com \ +78006003269 \ shop@lejournalintime.com \ 125493 Russia Moscow Avangardnaya street d3 office 1107',
        ],
        [
            'name' => 'Микроразметка (изображение)',
            'sort' => 1601,
            'group' => 'template_en',
            'path' => 'en/template_schema_image.php',
            'type' => 'image',
            'default' => '',
        ],
        [
            'name' => 'Заголовок H1',
            'sort' => 2001,
            'group' => 'home_en',
            'path' => 'en/main_h1.php',
            'type' => 'string',
            'default' => 'Winter Refresh: The Essential Sophia Lingerie',
        ],
        [
            'name' => 'Адрес флагманского магазина',
            'sort' => 2101,
            'group' => 'home_en',
            'path' => 'en/main_head_shop_address.php',
            'type' => 'string',
            'default' => 'Большая Никитская, 14',
        ],
        [
            'name' => 'Изображение флагманского магазина',
            'sort' => 2111,
            'group' => 'home_en',
            'path' => 'en/main_head_shop_image.php',
            'type' => 'image',
            'default' => '<img src="/assets/img/showroom-section/background-1.jpg" alt="" width="500">',
        ],
        [
            'name' => 'Доставка (модальное окно)',
            'sort' => 3001,
            'group' => 'product_en',
            'path' => 'en/product_modal_delivery.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/product_modal_delivery.php'),
        ],
        [
            'name' => 'Доставка: ссылка на условия возврата (модальное окно)',
            'sort' => 3101,
            'group' => 'product_en',
            'path' => 'en/product_modal_delivery_return_link.php',
            'type' => 'string',
            'default' => '',
        ],
        [
            'name' => 'Оплата (модальное окно)',
            'sort' => 3201,
            'group' => 'product_en',
            'path' => 'en/product_modal_payment.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/product_modal_payment.php'),
        ],
        [
            'name' => 'О нас',
            'sort' => 4001,
            'group' => 'about_en',
            'path' => 'en/about_intro.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/about_intro.php'),
        ],
        [
            'name' => 'Создатели',
            'sort' => 4101,
            'group' => 'about_en',
            'path' => 'en/about_vendor.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/about_vendor.php'),
        ],
        [
            'name' => 'Создатели (справа)',
            'sort' => 4101,
            'group' => 'about_en',
            'path' => 'en/about_vendor_2.php',
            'type' => 'html',
            'default' => '',
        ],
        [
            'name' => 'Признание в обществе',
            'sort' => 4201,
            'group' => 'about_en',
            'path' => 'en/about_media.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/about_media.php'),
        ],
        [
            'name' => 'Наши друзья',
            'sort' => 4401,
            'group' => 'about_en',
            'path' => 'en/about_friends.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/about_friends.php'),
        ],
        [
            'name' => 'Наименование компании',
            'sort' => 5001,
            'group' => 'contacts_en',
            'path' => 'en/contacts_company.php',
            'type' => 'string',
            'default' => 'ООО «Нэйтив»',
        ],
        [
            'name' => 'Реквизиты',
            'sort' => 5101,
            'group' => 'contacts_en',
            'path' => 'en/contacts_requisites.php',
            'type' => 'html',
            'default' => GetDefaultFromFile('en/contacts_requisites.php'),
        ],
        [
            'name' => 'Магазины партнеров (изображение)',
            'sort' => 6001,
            'group' => 'shops_en',
            'path' => 'en/shops_sales_locations.php',
            'type' => 'image',
            'default' => '<img src="/assets/img/showrooms/showroom-2.jpg" alt="" width="500">',
        ],
    ],
];
